name: butterfly

packages:
  - butterfly_cli
  - packages/**


scripts:
  analyze:
    exec: dart analyze .
  build:
    exec: dart build
  build_runner:
    exec: dart run build_runner build -d
    packageFilters:
      scope:
        - butterfly_cli
        - auth_management_database_isar_community
        - auth_management_provider_riverpod
        - core_management_route_go_router
  format:
    exec: dart format --set-exit-if-changed .
  update_deps:
    exec: dart pub upgrade
  update_deps_major:
    exec: dart pub upgrade --major-versions
  gen_version:
    exec: butterfly2 g version
    packageFilters:
      scope: butterfly_cli

command:
  version:
    hooks:
      post: melos run gen_version

ignore:
  - 'packages/**/example'
