name: butterfly_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  checked_yaml: ^2.0.3
  json_annotation: ^4.9.0
  mason_logger: ^0.3.1
  pub_semver: ^2.1.4
  pubspec_parse: ^1.3.0
  yaml_edit: ^2.2.1

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0

executables:
  butterfly2: butterfly_cli
